// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuDetails():Promise<string>;

export function GetCpuUsage():Promise<string>;

export function GetGpuDetails():Promise<string>;

export function GetRamDetails():Promise<string>;
