// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuDetails() {
  return window['go']['main']['App']['GetCpuDetails']();
}

export function GetCpuUsage() {
  return window['go']['main']['App']['GetCpuUsage']();
}

export function GetGpuDetails() {
  return window['go']['main']['App']['GetGpuDetails']();
}

export function GetRamDetails() {
  return window['go']['main']['App']['GetRamDetails']();
}
